name: DB2 Image

on:
 push:


jobs:
  build:
  
    runs-on: ubuntu-latest
    container: python:3.9
    steps:
    - name: Test network
      run: |
       curl 127.0.0.1:50000
    - name: Install sqlalchemy, ibm_db_sa
      run: |
        pip install --upgrade pip
        pip install sqlalchemy
        pip install ibm_db_sa
    - name: Checkout
      uses: actions/checkout@v3.5.2
    - name: Run Query
      run: |
        python run_db2_query.py
    
    
    services:
      ibm_db2:
        image: "icr.io/db2_community/db2"
        env:
          LICENSE: accept
          DB2INSTANCE: db2inst1
          DB2INST1_PASSWORD: password
          DBNAME: testdb
        options: "--privileged=true"
        ports:
          - 50000:50000
